POST http://localhost:8002/api/v1/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzU2MTc2ODgsInVzZXJfaWQiOiJmNTI2NzY5Zi03MGM2LTQ4N2QtODhmZS1mZjk3YTcyMDhlM2IiLCJ1dWlkIjoiZDk4Njc3MTItOGFiZi00MjBmLTgzYzEtMWUyOWYyNGEyNzUzIn0.Qodlx2PRbASK5eDtFVvHo8SUU2wd7IPX4PG4X77s-eQ
