POST http://localhost:8002/api/v1/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzUxMDYxMTksInVzZXJfaWQiOiI5NzQzYjEyMC01MDRiLTQ1MWEtYjgwYS03OWFmYzY3YjI2MjMiLCJ1dWlkIjoiNThiODUxOTYtY2EyNC00NzhhLWI2YTYtNjJlZDg4ZjEyYzU0In0.T1beD9cR22GuQUlT_9v2G6q9JY5K6ABUxzFazZ7wNeo
